### ISSUE TITLE
Feature request: send signed messages directly from the client

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/qdigidoc#11]
90% of the time signatures are used in web based context: pre-filled forms and other automated workflows. The rest is usually contracts and other "pdf and docx forms". Every now and then there is a need to send free form signed statements, for what right now the workflow goes like this:
- open notepad or similar
- write something
- save it
- open digidoc
- locate the file
- sign it
- ignore (not see) the "send by e-mail" link
- open mail client
- locate the signed file
- send it

Would be cool if I could just click "send signed message", write stuff to a textview, add e-mail and click "sign and send".

**Comment by martinl** [comment]
+1 for similar workflow in digidoc crypto

**Comment by metsma** [comment]
qdigidoc is now feature complete and no new development is made.
[DigiDoc4-Client](/open-eid/DigiDoc4-Client) supersedes qdigidoc
