### ISSUE TITLE
"Building in sandboxed environment" paragraph is prone to misunderstandings

### ISSUE THREAD

**Issue by Germano0** [open-eid/qdigidoc#144]
At page https://github.com/open-eid/qdigidoc/wiki/DeveloperTips#building-in-sandboxed-environment
you can read
![replace](https://user-images.githubusercontent.com/5477747/35966765-14cedab4-0cbf-11e8-81d6-9c9b45e8873b.jpg)

Since https://github.com/open-eid/qdigidoc/blob/master/client/CMakeLists.txt#L23
does not contain
` set( RC_FILES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
but it contains
`set_source_files_properties( Application_mac.mm PROPERTIES COMPILE_FLAGS "-fobjc-arc" )`
I think the paragraph is prone to misunderstandments, and IMHO it could be interpreted as:

**Option 1**
replace 
` set( RC_FILES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
and
`set_source_files_properties( Application_mac.mm PROPERTIES COMPILE_FLAGS "-fobjc-arc" )`
with
`set( RC_FILES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc TSL.qrc )`

**Option 2**
I look at
https://github.com/open-eid/qdigidoc/blob/master/client/CMakeLists.txt#L23
and I think "oh but the URL does not contain"
` set( RC_FILES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc ${CMAKE_CURRENT_BINARY_DIR}/TSL.qrc )`
that I saw right under the URL in the wiki page, but it contains
`set_source_files_properties( Application_mac.mm PROPERTIES COMPILE_FLAGS "-fobjc-arc" )`
and I don't know which one I have to replace with
` set( RC_FILES images/images.qrc ${CMAKE_CURRENT_BINARY_DIR}/tr.qrc TSL.qrc )`

**Comment by metsma** [comment]
Code is changed wiki outdated, please update and see how it is done in qesteidutil
https://github.com/open-eid/qesteidutil/tree/master/fedora

**Comment by Germano0** [comment]
> please update and see how it is done in qesteidutil
> https://github.com/open-eid/qesteidutil/tree/master/fedora

I am the author of the files in that URL :-)

**Comment by abitrolly** [comment]
@metsma maybe migrate the wiki to docs/ repository to make it updated with code?

**Comment by metsma** [comment]
This does not to resolve the problem, remember to update docs on code change. I will update the TSL part later

**Comment by Germano0** [comment]
TSL is the acronym of?

**Comment by metsma** [comment]
https://ec.europa.eu/digital-single-market/en/eu-trusted-lists-trust-service-providers

**Comment by metsma** [comment]
Updated the wiki

**Comment by Germano0** [comment]
Same with

> Replace line
> https://github.com/open-eid/qt-common/blob/master/CMakeLists.txt#L28
> `qt5_add_resources( SOURCES ${CMAKE_CURRENT_BINARY_DIR}/config.qrc )`

URL points to
`if( WIN32 )`
instead the code to replace is
`qt5_add_resources( SOURCES ${CMAKE_CURRENT_BINARY_DIR}/config.qrc )`

IMHO it would be better to quote the code to replace and simply mention the filename and path, without using URLs that become easly inconsistent after code updates

**Comment by abitrolly** [comment]
Can instructions to comment line be replaced with define. CMake probably supports them - at least `if( APPLE )` look like a define to me.

**Comment by abitrolly** [comment]
> This does not to resolve the problem, remember to update docs on code change.

But if anything in the process changes, it can be raised in PR. Commits can also be used to create cross-references between PRs and docs changes to make people aware of the docs.

> I will update the TSL part later

I can help with uploading it to Ethereum blockchain. )

**Comment by metsma** [comment]
Wiki updated
