### ISSUE TITLE
Coredump with Ubuntu 18.04

### ISSUE THREAD

**Issue by colourful-land** [open-eid/qdigidoc#164]
[digidoc-tool.1005.crash.gz](https://github.com/open-eid/qdigidoc/files/2386269/digidoc-tool.1005.crash.gz)

    $ /usr/local/bin/qdigidocclient
    Chache configuration serial: 68
    Bundled configuration serial: 68
    QObject: Cannot create children for a parent that is in a different thread.
    (Parent is QSigner(0x563f8775d460), parent's thread is QThread(0x563f873a6060), current thread is 
    QSigner(0x563f8775d460)
    Loading: "opensc-pkcs11.so"
    Violación de segmento (`core' generado)

The card reader and the card works on Mac OS and DigiDoc3 there.

I first suspected some problem with pkcs11 but it looks fine:

    $ pkcs11-tool -L
    Available slots:
    Slot 0 (0x0): Generic Smart Card Reader Interface [Smart Card Reader Interface
      token label        : PIN1 (ZHANG,WEIWU,38210270079)
      token manufacturer : AS Sertifitseerimiskeskus
      token model        : PKCS#15 emulated
      token flags        : login required, rng, token initialized, PIN initialized, user PIN locked
      hardware version   : 0.0
      firmware version   : 0.0
      serial num         : N0115068
      pin min/max        : 4/12
    Slot 1 (0x1): Generic Smart Card Reader Interface [Smart Card Reader Interface
      token label        : PIN2 (ZHANG,WEIWU,38210270079)
      token manufacturer : AS Sertifitseerimiskeskus
      token model        : PKCS#15 emulated
      token flags        : login required, rng, token initialized, PIN initialized
      hardware version   : 0.0
      firmware version   : 0.0
      serial num         : N0115068
      pin min/max        : 5/12

**Comment by colourful-land** [comment]
This problem can be reproduced in both of the following cases:

- with the standard-issued e-residency card reader from pluss-id.com
- with a known-working white-labelled card reader purchased from Singapore local market

**Comment by metsma** [comment]
Can you run under gdb debuger ja get backtrace

**Comment by colourful-land** [comment]
I can no longer reproduce the issue. In the last 2 weeks, I updated my Ubuntu a few times so the testbed isn't the same either. Sorry
