### ISSUE TITLE
openssl 1.1.1 support

### ISSUE THREAD

**Issue by arekm** [open-eid/qdigidoc#165]
openssl project released version 1.1.1 as new stable. Unfortunately API has changed and qdigidoc doesn't build with it.

This is feature request about adding support for current stable openssl 1.1.1.

**Comment by metsma** [comment]
Does Qt support openssl 1.1.1 already?

**Comment by arekm** [comment]
Depends on what you mean by "support". Tested qt5-qtbase (which contains qtnetworking) 5.11.1 build on Linux and it builds fine with openssl 1.1.1.

**Comment by metsma** [comment]
https://bugreports.qt.io/browse/QTBUG-67463 seems to have issues

**Comment by metsma** [comment]
can you post compiler errors, maybe it is easy fix

**Comment by arekm** [comment]
Looks like I tested some older version because latest 3.13.6 builds (with some small unrelated to openssl 1.1.1 fixes - https://git.pld-linux.org/gitweb.cgi?p=packages/qdigidoc.git;a=blob;f=build.patch;h=d2a05c0f1054dcdcd023b8af11ca2efe15705ceb;hb=HEAD)
