### ISSUE TITLE
Warning dialog in Eesti

### ISSUE THREAD

**Issue by abitrolly** [open-eid/qdigidoc#166]
I just got this message. What does it say?

![screenshot from 2018-11-05 13-40-23](https://user-images.githubusercontent.com/8781107/47993678-25313980-e101-11e8-8c5f-7cb2eb3faad9.png)

Is there a way to show such warnings in a dialog with language selection?

**Comment by abitrolly** [comment]
https://translate.google.com/#et/en/ID-kaardi%20baastarkvarast%20on%20saadaval%20uus%20versioon

The title says `The new version of the ID-card base software is available` but as you see, my version is 3.13.6.0 and [latest release](https://github.com/open-eid/qdigidoc/releases) is also 3.13.6?

What's going on? I am using Fedora 28.

**Comment by markus-kullerkup** [comment]
Digidoc3 client along with Utility and Digidoc3 crypto are EOL i.e all services remain functional however no new versions of these software will be released.
Digidoc4 client (which includes all funcionalities of Digidoc3, Utility and Crypto) is available to download via id.ee(supported Linux  distributions Ubuntu 16.04 (LTS), 18.04 (LTS) (64bit)

**Comment by abitrolly** [comment]
@markus-kullerkup do you mind updating repo description to state this fact and redirect to new version?
