### ISSUE TITLE
qdigidocclient: symbol lookup error: qdigidocclient: undefined symbol: _ZTIN7digidoc9XmlConfV3E

### ISSUE THREAD

**Issue by schryer** [open-eid/qdigidoc#3]
The compile and install completed without any errors on 14.10, however, running the resulting binary fails with the following error:

qdigidocclient: symbol lookup error: qdigidocclient: undefined symbol: _ZTIN7digidoc9XmlConfV3E

**Comment by smartman** [comment]
Same issue for me. Just installed digidoc from official script.
$ qdigidocclient 
qdigidocclient: symbol lookup error: qdigidocclient: undefined symbol: _ZTIN7digidoc9XmlConfV3E
$ uname -a
Linux margus-ThinkPad-T530 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by martinpaljak** [comment]
Checked to work correctly on Debian jessie and ubuntu 14.10. Make sure that you also have the dependencies (libdigidoc, libdigidocpp) from sibling-repositories of this organization, or you shall face issues. Debian and ubuntu distribute outdated and unmaintained forks unfortunately.

**Comment by martinpaljak** [comment]
And for binary package end-user support, please have a look at README.md

**Comment by smartman** [comment]
Installing below packages as recommended in this source repository fixed the issue.
`sudo apt-get install cmake qttools5-dev qttools5-dev-tools libpcsclite-dev libssl-dev libdigidocpp-dev`

**Comment by anroots** [comment]
I do think this should be handled by the installation script or the application - either by automatically installing the dependencies or by outputting a meaningful error message with a link where I could read more.
