### ISSUE TITLE
Please remove qdigidoc-cypto.appdata.xml file

### ISSUE THREAD

**Issue by mihkelvain** [open-eid/qdigidoc#59]
Hey.

Appdata has changed its policy and this renders qdigidoc-cypto.appdata.xml file obsolete, so please delete crypto/qdigidoc-cypto.appdata.xml file and remove 
`install( FILES qdigidoc-cypto.appdata.xml DESTINATION ${CMAKE_INSTALL_DATADIR}/appdata )	`
from crypto/CMakeLists.txt.

Sorry, but no pull request for that.

**Comment by metsma** [comment]
Any reference to this,or can you create PR?

**Comment by metsma** [comment]
Closing: No answer for weeks
