### ISSUE TITLE
Mac Sierra Install with Macports

### ISSUE THREAD

**Issue by siilats** [open-eid/qdigidoc#62]
When you install Qt with macports (sudo port install qt5) the compilation fails as /opt/local/libexec/qt5/include/ is not included. What I did was run cmake ..  (without the QtDir) and then edited the file in the cmake GUI to include the qt5/include in the SSL include folder (/opt/local/include;/opt/local/libexec/qt5/include) but I am sure there is a better way. 
Then I needed to install
https://github.com/open-eid/libdigidocpp/

**Comment by metsma** [comment]
You need pass cmake parameters to reference custom libs paths
With homebrew
cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .
