### ISSUE TITLE
[3.11.1] [abrt] qdigidoc: QXcbWindow::setParent(QPlatformWindow const*)(): qdigidocclient killed by SIGSEGV

### ISSUE THREAD

**Issue by Germano0** [open-eid/qdigidoc#7]
Hi, I am experiencing some crashes on 3.11.1 while using Fedora 23. You can find the ABRT attachments here  [https://bugzilla.redhat.com/show_bug.cgi?id=1295125](https://bugzilla.redhat.com/show_bug.cgi?id=1295125)

======== Red Hat Bugreport summary ========
Description of problem:
I clicked on "Sign documents" button, when the application crashed

Version-Release number of selected component:
qdigidoc-3.11.1.1427-1.fc23

Additional info:
reporter:       libreport-2.6.3
backtrace_rating: 4
cmdline:        qdigidocclient
crash_function: QXcbWindow::setParent(QPlatformWindow const*)
executable:     /usr/bin/qdigidocclient
global_pid:     21432
kernel:         4.2.8-300.fc23.x86_64
runlevel:       N 5
type:           CCpp
uid:            1000

**Comment by metsma** [comment]
Seems to be upstream bug

https://bugreports.qt.io/browse/QTBUG-50081
https://github.com/qtproject/qtbase/commit/eaa3a9d0108cdf692f1686cafefb7b834f0e5af6
