### ISSUE TITLE
General Linux installation instructions?

### ISSUE THREAD

**Issue by battlesnake** [open-eid/qdigidoc#8]
Not everyone uses Ubuntu!

```
CMake Error at /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibDigiDocpp (missing: LIBDIGIDOCPP_LIBRARY
  LIBDIGIDOCPP_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibDigiDocpp.cmake:20 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred
```

How do we find/install the dependencies on other distros (e.g. libdigidocpp)?

**Comment by metsma** [comment]
One option is building from source https://github.com/open-eid/libdigidocpp

**Comment by battlesnake** [comment]
I tried that, it has other missing dependencies - everything here seems to be very Ubuntu-specific

**Comment by metsma** [comment]
On witch OS you are compiling? There are also some 3rd party builds available
https://github.com/open-eid/linux-installer/wiki/Linux-Packages

**Comment by battlesnake** [comment]
I'm building for Arch - it might be useful to list URLs of dependencies (e.g. git/svn repositories, tarballs) in the installation instructions for packages rather than just the Ubuntu package names.

**Comment by metsma** [comment]
There is some work already done  https://wiki.archlinux.org/index.php/Estonian_ID-card need to update wiki

**Comment by battlesnake** [comment]
I used to use that - but in Firefox, it asked for both PIN codes when authenticating, and occasionally crashes the browser.  I had it working in Chrome until I recently rebuilt my laptop, but now can't seem to get that working properly again.

The original problem for this issue was a lack of general installation instructions though (not specific to any particular distribution).  Having general Linux installation instructions would avoid having to wade through dead links / out-dated packages / broken ports.

**Comment by metsma** [comment]
I think all 3rd party depended packages should already included in all distributions.
You only should match packages to target distribution.
Requirements for each component are also available.
If you have specific problem then you can open new ticket closing this for now.
Feel free to also create pull request for improving documentation.

**Comment by battlesnake** [comment]
`I think all 3rd party depended packages should already included in all distributions.`
Why would all distributions include smart-card packages by default?!

`You only should match packages to target distribution.`
I don't understand what you're trying to say there

`Requirements for each component are also available.`
As a list of Ubuntu package names.  Upstream URLs would be far more useful.

`If you have specific problem then you can open new ticket closing this for now.`
I thought I'd explained the problem quite well - you only seem to support Ubuntu.

`Feel free to also create pull request for improving documentation.`
I would, but given the total lack of Linux documentation, I don't have anywhere to start.

**Comment by metsma** [comment]
You can find URL-s from Windows/OSX section
https://github.com/open-eid/libdigidocpp
https://github.com/open-eid/qdigidoc

**Comment by metsma** [comment]
Also listed here http://open-eid.github.io/libdigidocpp/manual.html#Dependencies

**Comment by battlesnake** [comment]
Look in the Windows/OSX instructions for Linux information?  That makes total sense.......

**Comment by martinpaljak** [comment]
The dependencies are the same for OSX as they are for Linux (and Windows). So you can deduce any necessary steps and packages from that information. If you Linux distro does not have the necessary infrastructure (like smart card support) it might not be an easy journey. PR-s (or wiki suggestions) with documentation updates are most welcome.
