### ISSUE TITLE
Unable to validate signatures on a Lithuanian ADOC file

### ISSUE THREAD

**Issue by rimas-kudelis** [open-eid/qdigidoc#94]
I've installed `qdigidoc` on my Ubuntu 17.04 machine. I have some ADOC files which I wanted to check. The application opens both files and correctly shows signatures on them. However, the signatures are reported as either "not valid", or "unknown". Meanwhile the ISIGN/DigiDoc portal indicates that the signatures are valid and qualified.

Clicking on "Show details" next to the signature, and then "Technical information" reveals a few error messages:
for an invalid signature:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:541 Failed to validate signature: XPath transforms are not supported in this compilation of the XSEC library
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```

for an unknown signature:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:541 Failed to validate signature: XPath transforms are not supported in this compilation of the XSEC library
SignatureXAdES_B.cpp:736 Unable to verify signing certificate
X509CertStore.cpp:349 unable to get local issuer certificate
:0 
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```

I could send the ADOC files for debugging if necessary.

**Comment by tynisr** [comment]
can you please also  send the files?

**Comment by rimas-kudelis** [comment]
@tynisr I would prefer to send them by email, if that's OK.

**Comment by tynisr** [comment]
please send these to tonis.reimo at ria.ee

**Comment by rimas-kudelis** [comment]
Done

**Comment by metsma** [comment]
For the XPath error, ubuntu seems to missing xpath support in xml-security-c.
https://bugs.launchpad.net/ubuntu/+source/xml-security-c/+bug/1269434
Can you test compile xml-security-c package when xalan-c-dev is installed

**Comment by rimas-kudelis** [comment]
After recompilation, the XPath error is gone, but the signatures still fail to validate:
invalid signature:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata1.xml" failed to verify
Reference URI="metadata/signableMetadata1.xml" failed to verify

SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```

unknown signature:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify

SignatureXAdES_B.cpp:736 Unable to verify signing certificate
X509CertStore.cpp:349 unable to get local issuer certificate
:0 
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```

**Comment by metsma** [comment]
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
libdigidocpp currently expects to have timestamp attached. Seems like your signature is BES level?

**Comment by rimas-kudelis** [comment]
No, both signatures are qualified.

**Comment by metsma** [comment]
But do they contain timestamps?

**Comment by rimas-kudelis** [comment]
No, these signatures didn't, although I guess this is not required by the Adoc standard?

But I have a document with a signature with a timestamp as well. If fails to validate too (says signature is not valid):
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify

SignatureXAdES_LT.cpp:177 TimeStamp time and OCSP producedAt are over 15m TS: 20170713192844Z OCSP: 2017-05-22T08:52:44Z
```

**Comment by metsma** [comment]
Can you test, Windows or OSX prebuilt binaries if they give same result?

**Comment by rimas-kudelis** [comment]
Tomorrow maybe.
I can also forward you the files I sent to Tonis if you want.

**Comment by metsma** [comment]
Tõnis forwarded the files and one with TS validates as positive on OSX.
Did you get same result?

**Comment by rimas-kudelis** [comment]
I finally got around to testing this on **Windows** with the latest DigiDoc3 Client (3.13.1.1495). Indeed, document.adoc (the one with the timestamp) is shown as valid with warnings:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_LT.cpp:177 TimeStamp time and OCSP producedAt are over 15m TS: 20170808051813Z OCSP: 2017-07-12T05:23:09Z
```
The other document spots following errors for both signatures though:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```

**Comment by metsma** [comment]
I wonder what else can be different on windows and your environment?
Can you unzip the second file and verify if the UnsignedProperties is missing? If so then its BES signature

**Comment by rimas-kudelis** [comment]
For the same document.adoc (first file), DigiDoc3 Client version 3.13.1.1495 on Ubuntu 17.04 reports the signature as invalid:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify

SignatureXAdES_LT.cpp:177 TimeStamp time and OCSP producedAt are over 15m TS: 20170808074717Z OCSP: 2017-07-12T05:23:09Z
```
The signatures on the other document (20170621 RimasKudelis_Atsakymas_i_prasyma.adoc) are reported invalid as well:
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata1.xml" failed to verify
Reference URI="metadata/signableMetadata1.xml" failed to verify

SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```
and
```
SignatureXAdES_LTA.cpp:201 Signature validation
SignatureXAdES_B.cpp:457 Signature digest weak
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify

SignatureXAdES_B.cpp:736 Unable to verify signing certificate
X509CertStore.cpp:349 unable to get local issuer certificate
:0 
SignatureXAdES_T.cpp:171 QualifyingProperties block 'UnsignedProperties' is missing.
```
Regarding the latter document being BES: I thought we already concluded that it is BES, but does that make the signatures invalid?

Since this seems like more than one issue (one being Linux-specific, and the other one generic), maybe we should split this bug into two separate ones?

By the way, just a wild thought that has crossed my mind: could the Linux-specific issue be due to case-sensitive file system? The file systems for both Windows and OS X are case-insensitive AFAIR.

**Comment by rimas-kudelis** [comment]
Also, regarding this line:
```
SignatureXAdES_LT.cpp:177 TimeStamp time and OCSP producedAt are over 15m TS: 20170808074717Z OCSP: 2017-07-12T05:23:09Z
```
Why is the TimeStamp value always reporting current timestamp?

**Comment by metsma** [comment]
The software provider RIA requires that signatures should be XAdES T level.
Can you open please tickets to open-eid/libdigidocpp project, this is GUI code only.

Why is the TimeStamp value always reporting current timestamp?
Seems like bug in log, OCSP and TS times are switched. Can you create ticket to libdigidocpp for this?
https://github.com/open-eid/libdigidocpp/blob/15a83ba88e6292fff76d90e3da6e4944448012a0/src/SignatureXAdES_LT.cpp#L177

**Comment by rimas-kudelis** [comment]
Filed open-eid/libdigidocpp#142 and open-eid/libdigidocpp#143.
Regarding the XPath error: would you consider statically linking in the libraries necessary for this to work, until Debian/Ubuntu fix their packages?

**Comment by metsma** [comment]
I don't think we can statically link to libdigidocpp, we need provide probably own build xml-securiy-c packages which depend xalan-c. I will consult RIA

**Comment by rimas-kudelis** [comment]
Cool, that would work too! Just make sure to suffix the package version. :)

**Comment by rimas-kudelis** [comment]
Regarding the timestamp issue: would it be possible to have that requirement depend on a setting or toggle of some sort? I could file this as a separate feature request.

**Comment by metsma** [comment]
Probably yes, compile/configure option to minimum required validation level.

**Comment by rimas-kudelis** [comment]
Actually I meant a setting in the main window or settings dialog. Or is this unlikely?

**Comment by metsma** [comment]
Probably unlikely by upstream.
Maybe one possible way is to upgrade BES level to T level on validation like revocation info is taken and signing time is then validation time.

**Comment by metsma** [comment]
Can you create separate BES validation feature request to libdigidocpp.
Im closing this ticket, its not related qdigidoc GUI project
