### ISSUE TITLE
runtime dependency

### ISSUE THREAD

**Issue by fisher** [open-eid/qdigidoc#99]
The software didn't run as expected without opensc service running on background -- and debian/control didn't even mentioned dependency on `pcscd` package. It was kinda tricky to find the problem for a newcomer.

**Comment by metsma** [comment]
Ubuntu opensc depends on pcscd service https://packages.ubuntu.com/yakkety/opensc.
If debian is missing dependency then its upstream issue to fix issue

**Comment by fisher** [comment]
Yeah, of course, everyone should fix your problem xcept you. Thuck you for your help, mate.
I will not bother you anymore, rest in peace.

**Comment by metsma** [comment]
This is not correct place report upstream issues.
Please feel free report upstream issues to correct channel, debian, ubuntu, "name your favorite distro" or even opensc if it is needed.
